### PR TITLE
Upgrading to Quarkus 2

### PR DESCRIPTION
**Pull request by rmarting**
:sparkles: Quarkus 2.0.2.Final is the latest version of Quarkus, with a lot of great features, improvements added and issues fixed.

It should be great to use the latest version of Quarkus in this enablement about EDA, to achieve better knowledge, experience and enjoy with a faster :rocket: deployment and be a :smile: developer.

This PR includes the minium changes (:open_file_folder: basically structural ones) to upgrade the project to Quarkus 2.0.2.Final (or higher ones).

This PR resolves (not totally) the issue #15

### CODE REVIEW

**Comment by edeandrea** [comment]
FYI Quarkus `2.1.2.Final` is the current & most recent version.

**Comment by rmarting** [comment]
Thanks @edeandrea for the update.

Renamed this to cover the Quarkus 2 branch until is merged or to update to the latest one, as Quarkus is so much active and is publishing new releases in short time.

**Comment by psolarvi** [comment]
Thank you for the direct feedback. We are going to freeze all the course applications in the same Quarkus 2.x version. We will revisit this PR and apply the changes.

**Comment by m-czernek** [comment]
As a side note, I have used this branch as the basis for https://github.com/RedHatTraining/AD482-apps/pull/34, which superseeds this PR. TYVM for the contribution, it was helpful and I'm pushing parts of it to `main`.

**Comment by rmarting** [comment]
Great news @psolarvi and @m-czernek !!! I am glad to contribute to improve the labs of this enablament.

I guess that this PR will not be needed as you reintegrated the changes by the #34 PR, right? If you agree, then I could close it to avoid more conflicts. WDYT?

**Comment by m-czernek** [comment]
That is correct @rmarting. I have merged #34 . Thank you for your contribution :+1: Closing this PR.

**Pull request closed without merging**
